### ISSUE TITLE
Crash when viewing beehive tooltip in 1.19

### ISSUE THREAD

**Issue by gitchly** [bunten2005/tooltiptweaks-mod#2]
Game is freezing/crashing when checking the tooltip of a beehive with bees in it.

Playing on Minecraft 1.19 with Fabric Loader 0.14.8. 

Mods:
- Fabric API 0.56.0+1.19
- ModMenu 4.0.0
- Tooltip Tweaks 1.1.0

Crashlog:
```
---- Minecraft Crash Report ----
// Quite honestly, I wouldn't worry myself about that.

Time: 23/6/22, 2:08 pm
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2487.method_10550(String)" because the return value of "net.minecraft.class_1799.method_7941(String)" is null
	at Not Enough Crashes deobfuscated stack trace.(1.19+build.4)
	at net.bunten.tooltiptweaks.tooltip.ToolTooltips.addBeehiveTooltips(ToolTooltips.java:76)
	at net.bunten.tooltiptweaks.tooltip.ToolTooltips.addTooltips(ToolTooltips.java:102)
	at net.bunten.tooltiptweaks.TooltipTweaksMod.lambda$onInitializeClient$0(TooltipTweaksMod.java:50)
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:37)
	at net.minecraft.item.ItemStack.handler$bef000$getTooltip(ItemStack:4662)
	at net.minecraft.item.ItemStack.getTooltip(ItemStack:835)
	at net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.renderTooltip(CreativeInventoryScreen:698)
	at net.minecraft.client.gui.screen.ingame.HandledScreen.drawMouseoverTooltip(HandledScreen:189)
	at net.minecraft.client.gui.screen.ingame.CreativeInventoryScreen.render(CreativeInventoryScreen:692)
	at net.minecraft.client.render.GameRenderer.render(GameRenderer:881)
	at net.minecraft.client.MinecraftClient.render(MinecraftClient:1143)
	at net.minecraft.client.MinecraftClient.run(MinecraftClient:734)
	at net.minecraft.client.main.Main.main(Main:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.bunten.tooltiptweaks.tooltip.ToolTooltips.addBeehiveTooltips(ToolTooltips.java:76)
	at net.bunten.tooltiptweaks.tooltip.ToolTooltips.addTooltips(ToolTooltips.java:102)
	at net.bunten.tooltiptweaks.TooltipTweaksMod.lambda$onInitializeClient$0(TooltipTweaksMod.java:50)
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:37)
	at net.minecraft.class_1799.handler$bef000$getTooltip(class_1799.java:4662)
	at net.minecraft.class_1799.method_7950(class_1799.java:835)
	at net.minecraft.class_481.method_25409(class_481.java:698)
	at net.minecraft.class_465.method_2380(class_465.java:189)
	at net.minecraft.class_481.method_25394(class_481.java:692)

-- Screen render details --
Details:
	Screen name: net.minecraft.class_481
	Mouse location: Scaled: (337, 238). Absolute: (1013.000000, 715.000000)
	Screen size: Scaled: (640, 360). Absolute: (1920, 1080). Scale factor of 3.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)

-- Affected level --
Details:
	All players: 1 total; [class_746['SewerBunny'/261037, l='ClientLevel', x=-100.70, y=73.00, z=640.70]]
	Chunk stats: 4096, 2130
	Level dimension: minecraft:overworld
	Level spawn location: World: (0,70,0), Section: (at 0,6,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 5812 game time, 5812 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
	at java.base/java.lang.reflect.Method.invoke(Method.java:577)
	at org.multimc.impl.OneSixLauncher.invokeMain(OneSixLauncher.java:104)
	at org.multimc.impl.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:175)
	at org.multimc.impl.OneSixLauncher.launch(OneSixLauncher.java:185)
	at org.multimc.EntryPoint.listen(EntryPoint.java:127)
	at org.multimc.EntryPoint.main(EntryPoint.java:57)
```

**Comment by lunarbunten** [comment]
The fixes for this will be present in the next update.

**Comment by ardissaps** [comment]
1.18.2 please thanks! :)
